### ISSUE TITLE
Getting started has example for PHP 5.6 but it doesn't work

### ISSUE THREAD

**Issue by malaire** [sebastianbergmann/phpunit-website#24]
Page https://phpunit.de/getting-started.html has example for PHP 5.6 but it doesn't work because download instructions on that same page instructs to download phpunit which only supports PHP 7.

Either remove that example or provide instructions on how to download phpunit for PHP 5.6.

**Comment by sebastianbergmann** [comment]
Already fixed in 544ef1507748ce840bfb227f39524e4c84e0cede.
