### ISSUE TITLE
Adding two more libraries to "Extensions" page?

### ISSUE THREAD

**Issue by martin-helmich** [sebastianbergmann/phpunit-website#27]
Hello Sebastian,

I just noticed the "extensions" page on the PHPUnit website and was wondering if you'd be willing to accept pull requests to add a few more to that list. I'm asking since I've been sitting on a few PHPUnit extension libraries that I've been maintaining for a while now and I think might fit well into that list (more precisely, my [phpunit-json-assert](https://github.com/martin-helmich/phpunit-json-assert) and [phpunit-psr7-assert](https://github.com/martin-helmich/phpunit-psr7-assert) package).

Thoughts?

**Comment by keradus** [comment]
I would disrecommend adding custom assertions to website. If we would go that way, one would end up proposing hundreds of those custom assertion package.
If you believe that your assertions are generic and worth spreading, why not simply raising a PR to add them to main repo? :)

**Comment by sebastianbergmann** [comment]
Because I do not want to bloat PHPUnit (anymore).

**Comment by martin-helmich** [comment]
>I would disrecommend adding custom assertions to website. If we would go that way, one would end up proposing hundreds of those custom assertion package.

@keradus Thanks for the feedback. If not promoting third-party extensions, what other purpose does the "extensions" page serve?

**Comment by sebastianbergmann** [comment]
@martin-helmich Can you send a pull request, please?

**Comment by martin-helmich** [comment]
@sebastianbergmann :+1: Done

**Comment by sebastianbergmann** [comment]
I decided to remove the extensions page. I do not think (anymore) that such a list should be hosted on PHPUnit's website or that I should be the one curating it.
