### ISSUE TITLE
Wrong PHPUnit version with composer require command

### ISSUE THREAD

**Issue by Assertrex** [sebastianbergmann/phpunit-website#31]
Hi, I just wanted to tell about one mistake on a website, as I've lost about 2 hours because of it.

On: https://phpunit.de/getting-started/phpunit-7.html page, Composer command is: "**composer require --dev phpunit/phpunit ^7**", but (at least on Windows) this **^7** should be wrapped in **double quotes**.

Composer has set it as **"phpunit/phpunit": "7"**, and PHPStorm was warning me about unhandled exception on every assertion (due to 7.0.0 bug).

**Comment by keradus** [comment]
hm... I never had to use `"^7"`, `^7` was always enough.
Using Win 10 and Ubuntu, on both, works the same way

**Comment by Assertrex** [comment]
Then I don't know why it works like that, but when I wrap it with double quotes, it gets the right version. I've recently started using Composer so I don't know much about it.

![capture1](https://user-images.githubusercontent.com/12551655/39219411-95b42584-482a-11e8-95f5-44ccf9033a29.PNG)

**Comment by sebastianbergmann** [comment]
If at all, then this would be a Composer issue. Please report it there.
