### ISSUE TITLE
Requirements to publish on the extensions page.

### ISSUE THREAD

**Issue by andaniel05** [sebastianbergmann/phpunit-website#38]
Hi Sebastian.

It would be possible to elaborate a guide on the requirements that the extensions must fulfill so that they can appear published in the site ?.

I think that having that kind of information would help extension developers prepare our projects to make them publishable on the site.

My inquietude is that before I tried to publish an extension (https://github.com/andaniel05/PyramidalTests) but the pull-request was rejected and I am willing to adapt it to the publishing requirements that PHPUnit has. However I want to clarify that I respect any decision on whether it is not publishable on the site, but in general I think that having a requirements guide may be useful for new extensions.

Thank you

**Comment by sebastianbergmann** [comment]
I decided to remove the extensions page. I do not think (anymore) that such a list should be hosted on PHPUnit's website or that I should be the one curating it.
