### ISSUE TITLE
Documentation for 6.5 is down

### ISSUE THREAD

**Issue by unguul** [sebastianbergmann/phpunit-website#39]
https://phpunit.de/documentation.html points to https://phpunit.de/manual/6.5/en/index.html for documentation on older versions of phpunit but https://phpunit.de/manual/6.5/en/index.html returns 404.

**Comment by sebastianbergmann** [comment]
This is an unintentional side effect of a webserver configuration change I made yesterday. I will look into this and restore access to documentation for EOL versions of PHPUnit.

However, in the long run, this outdated information will be taken offline.

**Comment by unguul** [comment]
@sebastianbergmann Thank you!

Unfortunately, with Debian Buster still in development I will be stuck with 6.5 for a while. 

Am I correct when saying that the 6.5 documentation can be found at https://github.com/sebastianbergmann/phpunit-documentation ?
