### ISSUE TITLE
URLs to www.phpunit.de no longer work

### ISSUE THREAD

**Issue by Krinkle** [sebastianbergmann/phpunit-website#46]
Urls such as these:
* https://www.phpunit.de/manual/6.5/en/appendixes.annotations.html
* https://www.phpunit.de/manual/3.4/en/other-uses-for-tests.html

Now redirect to the homepage at <https://phpunit.de/>, which breaks existing URLs in books, blogs, toots, etc.

**Comment by sebastianbergmann** [comment]
I do not understand the "now" in your report.

If `www.` URLs worked in the recent past then this was by accident. The correct URLs for your examples would be `https://phpunit.de/manual/6.5/en/appendixes.annotations.html` and `https://phpunit.de/manual/3.4/en/other-uses-for-tests.html`.

I am not aware of any recent change to the configuration of the webserver that serves `phpunit.de` that would explain the "now".

Totally unrelated, but still: please note that both PHPUnit 3.4 and PHPUnit 6.5 are no longer supported and that the documentation for PHPUnit is now hosted [here](https://phpunit.readthedocs.io/).
