### ISSUE TITLE
Build Status

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit-website#47]
Once

* https://github.com/sebastianbergmann/php-code-coverage/issues/720
* https://github.com/sebastianbergmann/code-unit-reverse-lookup/issues/3
* https://github.com/sebastianbergmann/comparator/issues/75
* https://github.com/sebastianbergmann/diff/issues/93
* https://github.com/sebastianbergmann/environment/issues/54
* https://github.com/sebastianbergmann/exporter/issues/31
* https://github.com/sebastianbergmann/global-state/issues/28
* https://github.com/sebastianbergmann/object-enumerator/issues/7
* https://github.com/sebastianbergmann/object-reflector/issues/4
* https://github.com/sebastianbergmann/php-invoker/issues/11
* https://github.com/sebastianbergmann/php-timer/issues/25
* https://github.com/sebastianbergmann/php-token-stream/issues/87
* https://github.com/sebastianbergmann/recursion-context/issues/13
* https://github.com/sebastianbergmann/type/issues/7

have been addressed, we may need to update badges etc. on https://phpunit.de/build-status.html.

**Comment by localheinz** [comment]
I think that all of these issues have open/merged pull requests now!

**Comment by sebastianbergmann** [comment]
Great! Thank you for all your work on this, @localheinz.

**Comment by sebastianbergmann** [comment]
@localheinz I think I should take care of this. I have had the idea generate `build-status.html` with a simple PHP script (instead of manually maintaining the HTML) at the back of my mind for quite a while. I think I should finally implement it.

**Comment by localheinz** [comment]
@sebastianbergmann 

Sounds good!

**Comment by sebastianbergmann** [comment]
Thanks!
