### ISSUE TITLE
Add Open Graph

### ISSUE THREAD

**Issue by alexislefebvre** [sebastianbergmann/phpunit-website#50]
I shared these links on Slack:

- https://phpunit.de/announcements/phpunit-9.html
- https://phpunit.de/supported-versions.html

It didn't show previews of the links.

Open Graph tags would add the preview feature, on Slack but also Facebook, Twitter, etc.

Reference: https://fr.wikipedia.org/wiki/Open_Graph_Protocol

**Comment by sebastianbergmann** [comment]
I would consider a pull request for this but I will not work on this myself.
