### ISSUE TITLE
PHPUnit 11 PHAR file doesn't seem to be updated (yet)

### ISSUE THREAD

**Issue by jrfnl** [sebastianbergmann/phpunit-website#66]
On page: https://phpunit.de/getting-started/phpunit-11.html, the [link to the PHPUnit 11 PHAR file](https://phar.phpunit.de/phpunit-11.phar) is still serving PHPUnit 11.0.4, while 11.0.5 has been released earlier today.

Might just be a delay propagating ?

Figured I'd report it anyway in case that is not the problem.

**Comment by sebastianbergmann** [comment]
It's there :)

**Comment by jrfnl** [comment]
Thanks @sebastianbergmann ! Was the problem propagation ? Or was it something else ?

**Comment by sebastianbergmann** [comment]
Either a propagation issue or a caching issue.
