### ISSUE TITLE
PHPUnit 10/11 PHAR file doesn't seem to be updated (yet)

### ISSUE THREAD

**Issue by jrfnl** [sebastianbergmann/phpunit-website#69]
Similar to before (#66), the PHAR files from yesterday's release are not being served (site is still serving 10.5.35 and 11.4.0).

Maybe give the cache a gentle kick ?

**Comment by sebastianbergmann** [comment]
Must be a cache issue on your end, I am afraid. I checked https://phar.phpunit.de/ minutes after the release and the new releases were there.

**Comment by jrfnl** [comment]
That's weird as I checked a dozen times or so since the release. Oh well, will try again after Forum.
